inputDataDir: /home/ubuntu/workspace/mta_configs/
socrata_client_config_fname: socrata_config.yaml
pubtracker: _MTA_Publishing_Tracker.csv
attribute_list: MTA_FieldDocumentation_AttributeCompleteList.csv
agency_prefix: MTA
field_documentation_field: Field Documentation
feature_service_endpoint_field: Feature Service Endpoint
layer_field: Layer
category_field: Category
tags_field: Tags
type_field: Type
socrata_dataset_name_field: Socrata Dataset Name
layer_name_field: Layer Name
source_attribute_field: SourceAttribute
destination_attribute_field: DestinationAttribute
srid_projection: 4326
dataset_base_url: https://data.sfgov.org/resource/
dataset_dev_phase_field: Open Dataset
data_change_freq_field: Data Change Frequency
job_name: MTA Dataset Update
log_dir: /home/ubuntu/workspace/logs/
email_config_fname: email_config.yaml
exception_logfile: exception_log_mta_update.txt
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
geotype_field: Type
row_id_field: row_id
dataset_name_field: Socrata Dataset Name
description_field: description
isLoaded: isLoaded
column_field: socrataColumns
dataset_name_field: Socrata Dataset Name