inputDataDir: /home/ubuntu/workspace/mta_test/src_data/input/
socrata_client_config_fname: socrata_config.yaml
pubtracker: RP_PublishingTracker.csv
attribute_list: RP_FieldDocumentation_AttributeCompleteList.csv
agency_prefix: RP
field_documentation_field: Field Documentation
feature_service_endpoint_field: Feature Service Endpoint
layer_field: Layer
category_field: Category
tags_field: Tags
type_field: Type
socrata_dataset_name_field: Socrata Dataset Name
layer_name_field: Layer Name
source_attribute_field: SourceAttribute
destination_attribute_field: DestinationAttribute
srid_projection: 4326
dataset_base_url: https://data.sfgov.org/resource/